### ISSUE TITLE
Envato Market NOT COMPLIANT with WP 4.8

### ISSUE THREAD

**Issue by TheMarketingGuy** [envato/wp-envato-market#109]
Not only is the plugin not working properly for pushing theme updates for Goodlayers ->Infinity, it is only compliant to WP 4.5.

@envato-sites-systems @envato-systems  - FIX / UPDATE the plugin or PULL IT.

**Comment by JosKlever** [comment]
I'm using this plugin on multiple sites on various hosting platforms and also with WP 4.8, PHP 5.4-7.0, all kinds of themes en NO ISSUES.

The only issues I've seen so far were caused by theme/plugin makers that didn't supply the right installation files. So you need to contact the theme/plugin developer.

What you should check as well, is if you've installed Envato Market the right way using the following instructions: http://envato.github.io/wp-envato-market/
If the folder is anything else then "/wp-content/plugins/envato-market/", you downloaded the wrong file.

**Comment by aero2graph** [comment]
Not working.
"The OAuth Personal Token could not be verified. Please check that the Token has been entered correctly and has the minimum required permissions."

**Comment by drugurkocak** [comment]
It seems that theme installation via single use oauth personal token is not working any more.

[ınstall package not available](https://github.com/envato/wp-envato-market/issues/74)
[single use token not installing](https://github.com/envato/wp-envato-market/issues/64)

**Comment by dtbaker** [comment]
Hey @drugurkocak , @aero2graph , @JosKlever , @TheMarketingGuy  you are welcome to test the new version of the plugin.

Please delete the old `Envato Market` plugin from your WordPress installation and then add this attached plugin ZIP: 
[envato-market.zip](https://github.com/envato/wp-envato-market/files/1782074/envato-market.zip)
