### ISSUE TITLE
Still no updates

### ISSUE THREAD

**Issue by mensmaximus** [envato/wp-envato-market#123]
I wonder what is going on with the envato plugin. At the moment it is pretty useless due to the javascript bug not allowing updates. Although this is the official envato market plugin installed by many themes and plugins I can't see any progress in development. The plugin is still RC and bugs don't get fixed for month (years). Does envato not earn enough millions to pay some dollars to the developers? Shall we chip in for poor Mr. Collis Ta'eed? Can we now get feedback please about the further development of this plugin?

**Comment by Evelyn7** [comment]
I have begun complaining to the Theme Authors that sell their products via Envato in the hopes that they will also complain to Envato about this plugin not working. I have never received any replies from this Plugin Author to any of my tickets on this forum. Maybe, if everyone here complains to their Theme Authors about this plugin not working, then something will be done about it!

**Comment by mensmaximus** [comment]
I have sent a tweet to @envato and they replied:

> We're going to forward this to appropriate department and have them look into this for you. ^KW

**Comment by Evelyn7** [comment]
Wow! You actually got a response! Amazing!! You ROCK, @mensmaximus!! Hopefully, they will actually fix their required plugin!

**Comment by rolek** [comment]
Right Click the link, open in new tab... It will update. Use this workaround for now.

**Comment by Evelyn7** [comment]
Thank you for the suggestion. Yes, I have tried that in the past. It is not a consistent work-around for me....

**Comment by mensmaximus** [comment]
@rolek thanks but customers don't accept that. Still I am waiting for an official statement of the maintainers here and for a fix. I guess we have to start to send tweets to Mr. Ta'eed.

**Comment by networksolution** [comment]
Did you notice that you can update themes you've bought using the standard Wordpress update feature under: Dashboard > Update?

Btw, that bug is an easy fix.

**Comment by Evelyn7** [comment]
Yes, I did notice that update-ability and have used it when it is available. However, Envato/Code Canyon/Themefores/etc. requires us to have this "Envato Plugin"... which WAS working, but no longer does... So, is it no longer a "requirement"? That is my issue with this plugin. Why must I have it and "use" it when it no longer works? If it is no longer required, then why do they promote it? (Especially since it is not working and they seem to have abandoned it!) And, since no plugin author is responding to any thread/ticket on this forum (that I can tell), then why is the plugin still available at all? 
Personally, I have stopped installing it on my websites and have begun to remove it from the ones that I had it on...

**Comment by mensmaximus** [comment]
If everybody would send tweets to @envato_help on twitter every day we might get this sorted out

**Comment by dtbaker** [comment]
Hey @mensmaximus , @networksolution , @rolek  you are welcome to test the new version of the plugin.

Please delete the old `Envato Market` plugin from your WordPress installation and then add this attached plugin ZIP: 
[envato-market.zip](https://github.com/envato/wp-envato-market/files/1782074/envato-market.zip)
