### ISSUE TITLE
How Single Item Token Works?

### ISSUE THREAD

**Issue by digitalwordings** [envato/wp-envato-market#133]
Hello,

if i use single use token with item id, it can be hacked to use download all my items

**Comment by dtbaker** [comment]
Yes if a customer knew what they were doing they could technically download any of your purchased themes if you give them access to your API token. We recommend customers purchase their own items so that the item license is in the customer name, and also any API tokens are restricted to that customer. 

We hope to release a new oAuth feature that authors can integrate with so that the use of individual API tokens is no longer require.
