### ISSUE TITLE
ERROR: You do not have sufficient permissions to delete transients

### ISSUE THREAD

**Issue by haleeben** [envato/wp-envato-market#33]
Hi

When the plugin is activated, if I try to update other plugins or do some other actions I get the error

"You do not have sufficient permissions to delete transients"

If I deactivate the Envato Market plugin the error goes away.

**Comment by valendesigns** [comment]
You have a version of the plugin that you shouldn't have and should update. That version of 1.0.0-beta https://github.com/envato/wp-envato-market/commit/2274d3fecf997c743d88b20c4041dc00202b1a90 was only downloadable for a few hours and was fixed in this commit https://github.com/envato/wp-envato-market/commit/fa0e51246d3ba7c5f77793c065a568d304134333 please update to the latest version. Reopen if that doesn't fix the issue.
