### ISSUE TITLE
Not All Envato Plugins are showing up

### ISSUE THREAD

**Issue by sloantech** [envato/wp-envato-market#54]
WP Envato Market installed fine. The Global OAuth Personal Token was obtained fine. The 'Test API' worked fine. BUT only only 1 of many plugins are showing up in the plugins tab - why?

Is there anyone updating this "WP Envato Market" plugin or even monitoring the problems people are having with it?

**Comment by sloantech** [comment]
Why no support?

**Comment by cogdog** [comment]
I am missing one of my purchased plugins as well- this is what I see in Wordpress, only 2 plugins:

![plugins](https://cloud.githubusercontent.com/assets/463038/16528154/d97f1122-3f6f-11e6-99d3-1986bf517338.jpg)

Yet I do not see the Wordpress Social Stream plugin I have purchased:

![codecanyon](https://cloud.githubusercontent.com/assets/463038/16528166/ee9da49c-3f6f-11e6-889a-3ca477e964e9.jpg)

When i try adding it as a single item Oauth, using my API token and the item ID copied from my purchase, it tells me that one them is invalid.

Which puts me back to manual updates.

**Comment by valendesigns** [comment]
The plugin probably does not have an installable WordPress package. Please verify that it does.

**Comment by cogdog** [comment]
Thanks. I'm not quite sure what that means, but inside the zip download from Codecanyon, I get documentation, the unpackaged plugin, and a zip-package of the plugin:

![installable](https://cloud.githubusercontent.com/assets/463038/16538295/10bc21ba-3fd5-11e6-86e7-2139c352e36a.jpg)

If this is not correct, isnt this something Code Canyon ought to be dealing with the developer, not me as a customer?

**Comment by valendesigns** [comment]
The author has the option to upload the package separate but some don't. Ask the author to add one.

**Comment by highacid** [comment]
I have the same issue with some of the plugins missing from the envator market in wordpress. What can I do?

**Comment by cogdog** [comment]
From what I understand there is not much we can do. The problem is that the download .zip packages for these plugins often include documentation and other materials, and includes the plugin package itself, another ZIP, the one that actually installs the plugin in Wordpress.

Themes I have purchased on envato have multiple install downloads - ones that include everything, and a separate one that just the includes the files that need to be installed on Wordpress. Apparently plugins on envato sites are not set up this way. It sounds like one has to make a request to the plugin developer to include a download that are the Wordpress files only.  It would be worth sending feedback to enavto too.

I am only guessing.

**Comment by valendesigns** [comment]
Plugins are setup the same way as themes, it's just that authors are not required to include the WP package. I think that should change and they should be required to add this installable download to any future updates. However, that is for Envato to decide, I am only the developer of this plugin and in no way make decisions about the Envato Marketplace.

**Comment by cogdog** [comment]
Thanks for that, I will be sure to leave feedback for Envato to encourage
this requirement.

On Fri, Jul 8, 2016 at 2:46 PM, Derek Herman <notifications@github.com>
wrote:

> Plugins are setup the same way as themes, it's just that authors are not
> required to include the WP package. I think that should change and they
> should be required to add this installable download to any future updates.
> However, that is for Envato to decide, I am only the developer of this
> plugin and in no way make decisions about the Envato Marketplace.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/envato/wp-envato-market/issues/54#issuecomment-231480802>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAcQvjOs-xWB5OwJlzzpkzmQQi4wqGbyks5qTsUogaJpZM4I9XcS>
> .
>



-- 


*------------------------------------------------------------------------------------Alan
Levine: A Cog, A Dog, A Blog *
cog.dog • yep, that's my domain!

blog: cogdogblog.com  • tweets: @cogdog <http://twitter.com/cogdog>

photos: flickr <http://flickr.com/photos/cogdog> & Barking Dog Studios
<http://barkingdog.me> • code: github.com/cogdog
50+ Web Ways to Tell a Story <http://50ways.wikispaces.com> • pechaflickr
<http://pechaflickr.net> • ds106 <http://ds106.us/>
*------------------------------------------------------------------------------------*

**Comment by tmacka88** [comment]
I have a similar issue, though don't think its the same.

Only 9 plugins and 9 themes show up when I have more. Does it limit to only show the first 9 plugins/themes?

**Comment by duongancol** [comment]
Yes, the same problem here

**Comment by tmacka88** [comment]
So what they are saying above is actually the issue. Because the theme or plugin developers are only uploading a zip with other files in it (documents, read etc) to envato, this plugin can not pick them up. You have to get in touch with the developers and get them to upload a zip with only the plugin in it to envato. You can check this by login into enviro click download and you have some options installable version or all files version. If it has the installable version then this plugin should pick it up.

**Comment by dtbaker** [comment]
@sloantech @dashc @duongancol etc.. this is a rather old issue, we've made a few API changes and are wondering if this is still happening? If so please feel free to re-open this issue with details and we can investigate & fix.
